### ISSUE TITLE
Can stefcal account for missing antennas?

### ISSUE THREAD

**Issue by Chuneeta** [Trienko/heracommissioning#1]
Some antennas were removed from the PAPER datasets since they were dysfunctional and the stefcal redundant calibration does not seem to be working if there are missing antennas.

**Comment by giannibernardi** [comment]
if you convert to MS the original files there shouldn't be any missing
antenna. I believe Trienko has implemented the fact that an antenna can be
flagged...
Before you go too deep into redundant cal we should look at the final
results you get from sky calibration...

On Thu, Sep 7, 2017 at 12:48 PM, Nunhokee Chuneeta <notifications@github.com
